version: '3.9'
services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "admin_password"
      DATABASE_NAME: "evolution_db"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: evolution_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin_password"
      POSTGRES_DB: "evolution_db"
