version: '3.9'
services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "admin_password"
      DATABASE_NAME: "evolution_db"
      AUTHENTICATION_API_KEY: "minha-chave-secreta"
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://evolution_redis:6379"
      CACHE_REDIS_PREFIX_KEY: "evolution"
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:14
    container_name: evolution_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin_password"
      POSTGRES_DB: "evolution_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
